# Generated by Django 2.1.1 on 2018-11-03 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='interestes',
            new_name='interests',
        ),
    ]
