sudo: required

matrix:
    include:
      - language: node_js
        node_js:
          - "8"
        before_install:
          - cd Moisha-Front
        install:
          - npm install -g @angular/cli
          - npm install
        script:
          - npm test

      - language: python
        python: 3.6
        before_install:
          - cd Moisha_Back
        install:
          - pip install -r requirements.txt
        script:
          - python manage.py test

