sudo: required

matrix:
    include:
      - language: node_js
        node_js:
          - "8"
        before_install:
          - cd Moisha_Front
        install:
          - npm install -g @angular/cli
          - npm install
        script:
          - npm test

      - language: python
        python: 3.6
        install:
          - pip install -r Moisha_Back/requirements.txt
        script:
          - coverage run Moisha_Back/manage.py test

