# Generated by Django 2.1.1 on 2018-11-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletag',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
