# Generated by Django 2.1.1 on 2018-11-05 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20181103_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('rgb', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A_F]{6}$')])),
            ],
        ),
    ]
