# Generated by Django 2.1.1 on 2018-11-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_articletag_rgb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articletag',
            old_name='rgb',
            new_name='color',
        ),
    ]
