# Generated by Django 2.1.2 on 2018-11-30 03:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20181105_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='createdDate',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now),
        ),
    ]
