# Generated by Django 2.1.1 on 2018-11-06 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20181105_2224'),
        ('interest', '0003_interest_createuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='interesttag',
            name='color',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to='article.TagColor'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='photoURL',
            field=models.CharField(default='https://raw.githubusercontent.com/swsnu/swpp18-team2/master/Images/empty.png', max_length=140),
        ),
    ]
