# Generated by Django 2.1.1 on 2018-11-06 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0004_auto_20181106_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
