# Generated by Django 2.1.1 on 2018-11-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0005_auto_20181106_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='detail',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
