# Generated by Django 2.1.1 on 2018-11-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0008_auto_20181107_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='photoURL',
            field=models.CharField(default='https://raw.githubusercontent.com/swsnu/swpp18-team2/master/Images/empty.png', max_length=500),
        ),
    ]
