# Generated by Django 2.1.1 on 2018-12-04 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0010_auto_20181107_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestJaccard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(db_index=True, default=0.0)),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='interest.Interest')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interest.Interest')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='interestjaccard',
            unique_together={('first', 'second')},
        ),
    ]
