# Generated by Django 2.1.2 on 2018-12-08 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interest', '0011_auto_20181204_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='managers',
            field=models.ManyToManyField(related_name='manage_interests', to=settings.AUTH_USER_MODEL),
        ),
    ]
